id: A1124D948
title: Concise Consecration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:19:29.943198
  last_modified_at: 2022-03-01 03:19:29.943202
