id: A1124D948
title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
  of Enlightened Body, Speech and Mind'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:19:29.944828
  last_modified_at: 2022-03-01 03:19:29.944831
