id: A1124D948
title: A Brief Ritual for Consecrating Representations of Enlightened Body, Speech
  and Mind
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:19:29.941067
  last_modified_at: 2022-03-01 03:19:29.941082
